server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: true

spring:
  application:
    name: hours
  datasource:
    url: jdbc:postgresql://localhost:5432/desafio-greenmile
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
    show-sql: false

jwt:
  config:
    type: signed