language: java
jdk: oraclejdk8

dist: trusty

addons:
  sonarcloud:
    organization: "robsonsilv4_desafioGreenMile"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar