server:
  port: 8083

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: true

spring:
  application:
    name: auth
  jmx:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/desafio-greenmile
    password: postgres
    username: postgres
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  config:
    type: signed